
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `StoreStatistic` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model StoreStatistic
 * 
 */
export type StoreStatisticModel = runtime.Types.Result.DefaultSelection<Prisma.$StoreStatisticPayload>

export type AggregateStoreStatistic = {
  _count: StoreStatisticCountAggregateOutputType | null
  _avg: StoreStatisticAvgAggregateOutputType | null
  _sum: StoreStatisticSumAggregateOutputType | null
  _min: StoreStatisticMinAggregateOutputType | null
  _max: StoreStatisticMaxAggregateOutputType | null
}

export type StoreStatisticAvgAggregateOutputType = {
  id: number | null
  storeId: number | null
  booksFound: number | null
}

export type StoreStatisticSumAggregateOutputType = {
  id: number | null
  storeId: number | null
  booksFound: number | null
}

export type StoreStatisticMinAggregateOutputType = {
  id: number | null
  storeId: number | null
  booksFound: number | null
  lastScrapedAt: Date | null
}

export type StoreStatisticMaxAggregateOutputType = {
  id: number | null
  storeId: number | null
  booksFound: number | null
  lastScrapedAt: Date | null
}

export type StoreStatisticCountAggregateOutputType = {
  id: number
  storeId: number
  booksFound: number
  lastScrapedAt: number
  _all: number
}


export type StoreStatisticAvgAggregateInputType = {
  id?: true
  storeId?: true
  booksFound?: true
}

export type StoreStatisticSumAggregateInputType = {
  id?: true
  storeId?: true
  booksFound?: true
}

export type StoreStatisticMinAggregateInputType = {
  id?: true
  storeId?: true
  booksFound?: true
  lastScrapedAt?: true
}

export type StoreStatisticMaxAggregateInputType = {
  id?: true
  storeId?: true
  booksFound?: true
  lastScrapedAt?: true
}

export type StoreStatisticCountAggregateInputType = {
  id?: true
  storeId?: true
  booksFound?: true
  lastScrapedAt?: true
  _all?: true
}

export type StoreStatisticAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which StoreStatistic to aggregate.
   */
  where?: Prisma.StoreStatisticWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of StoreStatistics to fetch.
   */
  orderBy?: Prisma.StoreStatisticOrderByWithRelationInput | Prisma.StoreStatisticOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.StoreStatisticWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` StoreStatistics from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` StoreStatistics.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned StoreStatistics
  **/
  _count?: true | StoreStatisticCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: StoreStatisticAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: StoreStatisticSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: StoreStatisticMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: StoreStatisticMaxAggregateInputType
}

export type GetStoreStatisticAggregateType<T extends StoreStatisticAggregateArgs> = {
      [P in keyof T & keyof AggregateStoreStatistic]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateStoreStatistic[P]>
    : Prisma.GetScalarType<T[P], AggregateStoreStatistic[P]>
}




export type StoreStatisticGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.StoreStatisticWhereInput
  orderBy?: Prisma.StoreStatisticOrderByWithAggregationInput | Prisma.StoreStatisticOrderByWithAggregationInput[]
  by: Prisma.StoreStatisticScalarFieldEnum[] | Prisma.StoreStatisticScalarFieldEnum
  having?: Prisma.StoreStatisticScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: StoreStatisticCountAggregateInputType | true
  _avg?: StoreStatisticAvgAggregateInputType
  _sum?: StoreStatisticSumAggregateInputType
  _min?: StoreStatisticMinAggregateInputType
  _max?: StoreStatisticMaxAggregateInputType
}

export type StoreStatisticGroupByOutputType = {
  id: number
  storeId: number
  booksFound: number
  lastScrapedAt: Date
  _count: StoreStatisticCountAggregateOutputType | null
  _avg: StoreStatisticAvgAggregateOutputType | null
  _sum: StoreStatisticSumAggregateOutputType | null
  _min: StoreStatisticMinAggregateOutputType | null
  _max: StoreStatisticMaxAggregateOutputType | null
}

type GetStoreStatisticGroupByPayload<T extends StoreStatisticGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<StoreStatisticGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof StoreStatisticGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], StoreStatisticGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], StoreStatisticGroupByOutputType[P]>
      }
    >
  >



export type StoreStatisticWhereInput = {
  AND?: Prisma.StoreStatisticWhereInput | Prisma.StoreStatisticWhereInput[]
  OR?: Prisma.StoreStatisticWhereInput[]
  NOT?: Prisma.StoreStatisticWhereInput | Prisma.StoreStatisticWhereInput[]
  id?: Prisma.IntFilter<"StoreStatistic"> | number
  storeId?: Prisma.IntFilter<"StoreStatistic"> | number
  booksFound?: Prisma.IntFilter<"StoreStatistic"> | number
  lastScrapedAt?: Prisma.DateTimeFilter<"StoreStatistic"> | Date | string
  store?: Prisma.XOR<Prisma.StoreScalarRelationFilter, Prisma.StoreWhereInput>
}

export type StoreStatisticOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  storeId?: Prisma.SortOrder
  booksFound?: Prisma.SortOrder
  lastScrapedAt?: Prisma.SortOrder
  store?: Prisma.StoreOrderByWithRelationInput
}

export type StoreStatisticWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  storeId?: number
  AND?: Prisma.StoreStatisticWhereInput | Prisma.StoreStatisticWhereInput[]
  OR?: Prisma.StoreStatisticWhereInput[]
  NOT?: Prisma.StoreStatisticWhereInput | Prisma.StoreStatisticWhereInput[]
  booksFound?: Prisma.IntFilter<"StoreStatistic"> | number
  lastScrapedAt?: Prisma.DateTimeFilter<"StoreStatistic"> | Date | string
  store?: Prisma.XOR<Prisma.StoreScalarRelationFilter, Prisma.StoreWhereInput>
}, "id" | "storeId">

export type StoreStatisticOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  storeId?: Prisma.SortOrder
  booksFound?: Prisma.SortOrder
  lastScrapedAt?: Prisma.SortOrder
  _count?: Prisma.StoreStatisticCountOrderByAggregateInput
  _avg?: Prisma.StoreStatisticAvgOrderByAggregateInput
  _max?: Prisma.StoreStatisticMaxOrderByAggregateInput
  _min?: Prisma.StoreStatisticMinOrderByAggregateInput
  _sum?: Prisma.StoreStatisticSumOrderByAggregateInput
}

export type StoreStatisticScalarWhereWithAggregatesInput = {
  AND?: Prisma.StoreStatisticScalarWhereWithAggregatesInput | Prisma.StoreStatisticScalarWhereWithAggregatesInput[]
  OR?: Prisma.StoreStatisticScalarWhereWithAggregatesInput[]
  NOT?: Prisma.StoreStatisticScalarWhereWithAggregatesInput | Prisma.StoreStatisticScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"StoreStatistic"> | number
  storeId?: Prisma.IntWithAggregatesFilter<"StoreStatistic"> | number
  booksFound?: Prisma.IntWithAggregatesFilter<"StoreStatistic"> | number
  lastScrapedAt?: Prisma.DateTimeWithAggregatesFilter<"StoreStatistic"> | Date | string
}

export type StoreStatisticCreateInput = {
  booksFound?: number
  lastScrapedAt?: Date | string
  store: Prisma.StoreCreateNestedOneWithoutStatisticsInput
}

export type StoreStatisticUncheckedCreateInput = {
  id?: number
  storeId: number
  booksFound?: number
  lastScrapedAt?: Date | string
}

export type StoreStatisticUpdateInput = {
  booksFound?: Prisma.IntFieldUpdateOperationsInput | number
  lastScrapedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  store?: Prisma.StoreUpdateOneRequiredWithoutStatisticsNestedInput
}

export type StoreStatisticUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  storeId?: Prisma.IntFieldUpdateOperationsInput | number
  booksFound?: Prisma.IntFieldUpdateOperationsInput | number
  lastScrapedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type StoreStatisticCreateManyInput = {
  id?: number
  storeId: number
  booksFound?: number
  lastScrapedAt?: Date | string
}

export type StoreStatisticUpdateManyMutationInput = {
  booksFound?: Prisma.IntFieldUpdateOperationsInput | number
  lastScrapedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type StoreStatisticUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  storeId?: Prisma.IntFieldUpdateOperationsInput | number
  booksFound?: Prisma.IntFieldUpdateOperationsInput | number
  lastScrapedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type StoreStatisticNullableScalarRelationFilter = {
  is?: Prisma.StoreStatisticWhereInput | null
  isNot?: Prisma.StoreStatisticWhereInput | null
}

export type StoreStatisticCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  storeId?: Prisma.SortOrder
  booksFound?: Prisma.SortOrder
  lastScrapedAt?: Prisma.SortOrder
}

export type StoreStatisticAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  storeId?: Prisma.SortOrder
  booksFound?: Prisma.SortOrder
}

export type StoreStatisticMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  storeId?: Prisma.SortOrder
  booksFound?: Prisma.SortOrder
  lastScrapedAt?: Prisma.SortOrder
}

export type StoreStatisticMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  storeId?: Prisma.SortOrder
  booksFound?: Prisma.SortOrder
  lastScrapedAt?: Prisma.SortOrder
}

export type StoreStatisticSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  storeId?: Prisma.SortOrder
  booksFound?: Prisma.SortOrder
}

export type StoreStatisticCreateNestedOneWithoutStoreInput = {
  create?: Prisma.XOR<Prisma.StoreStatisticCreateWithoutStoreInput, Prisma.StoreStatisticUncheckedCreateWithoutStoreInput>
  connectOrCreate?: Prisma.StoreStatisticCreateOrConnectWithoutStoreInput
  connect?: Prisma.StoreStatisticWhereUniqueInput
}

export type StoreStatisticUncheckedCreateNestedOneWithoutStoreInput = {
  create?: Prisma.XOR<Prisma.StoreStatisticCreateWithoutStoreInput, Prisma.StoreStatisticUncheckedCreateWithoutStoreInput>
  connectOrCreate?: Prisma.StoreStatisticCreateOrConnectWithoutStoreInput
  connect?: Prisma.StoreStatisticWhereUniqueInput
}

export type StoreStatisticUpdateOneWithoutStoreNestedInput = {
  create?: Prisma.XOR<Prisma.StoreStatisticCreateWithoutStoreInput, Prisma.StoreStatisticUncheckedCreateWithoutStoreInput>
  connectOrCreate?: Prisma.StoreStatisticCreateOrConnectWithoutStoreInput
  upsert?: Prisma.StoreStatisticUpsertWithoutStoreInput
  disconnect?: Prisma.StoreStatisticWhereInput | boolean
  delete?: Prisma.StoreStatisticWhereInput | boolean
  connect?: Prisma.StoreStatisticWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.StoreStatisticUpdateToOneWithWhereWithoutStoreInput, Prisma.StoreStatisticUpdateWithoutStoreInput>, Prisma.StoreStatisticUncheckedUpdateWithoutStoreInput>
}

export type StoreStatisticUncheckedUpdateOneWithoutStoreNestedInput = {
  create?: Prisma.XOR<Prisma.StoreStatisticCreateWithoutStoreInput, Prisma.StoreStatisticUncheckedCreateWithoutStoreInput>
  connectOrCreate?: Prisma.StoreStatisticCreateOrConnectWithoutStoreInput
  upsert?: Prisma.StoreStatisticUpsertWithoutStoreInput
  disconnect?: Prisma.StoreStatisticWhereInput | boolean
  delete?: Prisma.StoreStatisticWhereInput | boolean
  connect?: Prisma.StoreStatisticWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.StoreStatisticUpdateToOneWithWhereWithoutStoreInput, Prisma.StoreStatisticUpdateWithoutStoreInput>, Prisma.StoreStatisticUncheckedUpdateWithoutStoreInput>
}

export type StoreStatisticCreateWithoutStoreInput = {
  booksFound?: number
  lastScrapedAt?: Date | string
}

export type StoreStatisticUncheckedCreateWithoutStoreInput = {
  id?: number
  booksFound?: number
  lastScrapedAt?: Date | string
}

export type StoreStatisticCreateOrConnectWithoutStoreInput = {
  where: Prisma.StoreStatisticWhereUniqueInput
  create: Prisma.XOR<Prisma.StoreStatisticCreateWithoutStoreInput, Prisma.StoreStatisticUncheckedCreateWithoutStoreInput>
}

export type StoreStatisticUpsertWithoutStoreInput = {
  update: Prisma.XOR<Prisma.StoreStatisticUpdateWithoutStoreInput, Prisma.StoreStatisticUncheckedUpdateWithoutStoreInput>
  create: Prisma.XOR<Prisma.StoreStatisticCreateWithoutStoreInput, Prisma.StoreStatisticUncheckedCreateWithoutStoreInput>
  where?: Prisma.StoreStatisticWhereInput
}

export type StoreStatisticUpdateToOneWithWhereWithoutStoreInput = {
  where?: Prisma.StoreStatisticWhereInput
  data: Prisma.XOR<Prisma.StoreStatisticUpdateWithoutStoreInput, Prisma.StoreStatisticUncheckedUpdateWithoutStoreInput>
}

export type StoreStatisticUpdateWithoutStoreInput = {
  booksFound?: Prisma.IntFieldUpdateOperationsInput | number
  lastScrapedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type StoreStatisticUncheckedUpdateWithoutStoreInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  booksFound?: Prisma.IntFieldUpdateOperationsInput | number
  lastScrapedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type StoreStatisticSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  storeId?: boolean
  booksFound?: boolean
  lastScrapedAt?: boolean
  store?: boolean | Prisma.StoreDefaultArgs<ExtArgs>
}, ExtArgs["result"]["storeStatistic"]>

export type StoreStatisticSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  storeId?: boolean
  booksFound?: boolean
  lastScrapedAt?: boolean
  store?: boolean | Prisma.StoreDefaultArgs<ExtArgs>
}, ExtArgs["result"]["storeStatistic"]>

export type StoreStatisticSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  storeId?: boolean
  booksFound?: boolean
  lastScrapedAt?: boolean
  store?: boolean | Prisma.StoreDefaultArgs<ExtArgs>
}, ExtArgs["result"]["storeStatistic"]>

export type StoreStatisticSelectScalar = {
  id?: boolean
  storeId?: boolean
  booksFound?: boolean
  lastScrapedAt?: boolean
}

export type StoreStatisticOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "storeId" | "booksFound" | "lastScrapedAt", ExtArgs["result"]["storeStatistic"]>
export type StoreStatisticInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  store?: boolean | Prisma.StoreDefaultArgs<ExtArgs>
}
export type StoreStatisticIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  store?: boolean | Prisma.StoreDefaultArgs<ExtArgs>
}
export type StoreStatisticIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  store?: boolean | Prisma.StoreDefaultArgs<ExtArgs>
}

export type $StoreStatisticPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "StoreStatistic"
  objects: {
    store: Prisma.$StorePayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    storeId: number
    booksFound: number
    lastScrapedAt: Date
  }, ExtArgs["result"]["storeStatistic"]>
  composites: {}
}

export type StoreStatisticGetPayload<S extends boolean | null | undefined | StoreStatisticDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$StoreStatisticPayload, S>

export type StoreStatisticCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<StoreStatisticFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: StoreStatisticCountAggregateInputType | true
  }

export interface StoreStatisticDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['StoreStatistic'], meta: { name: 'StoreStatistic' } }
  /**
   * Find zero or one StoreStatistic that matches the filter.
   * @param {StoreStatisticFindUniqueArgs} args - Arguments to find a StoreStatistic
   * @example
   * // Get one StoreStatistic
   * const storeStatistic = await prisma.storeStatistic.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends StoreStatisticFindUniqueArgs>(args: Prisma.SelectSubset<T, StoreStatisticFindUniqueArgs<ExtArgs>>): Prisma.Prisma__StoreStatisticClient<runtime.Types.Result.GetResult<Prisma.$StoreStatisticPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one StoreStatistic that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {StoreStatisticFindUniqueOrThrowArgs} args - Arguments to find a StoreStatistic
   * @example
   * // Get one StoreStatistic
   * const storeStatistic = await prisma.storeStatistic.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends StoreStatisticFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, StoreStatisticFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__StoreStatisticClient<runtime.Types.Result.GetResult<Prisma.$StoreStatisticPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first StoreStatistic that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StoreStatisticFindFirstArgs} args - Arguments to find a StoreStatistic
   * @example
   * // Get one StoreStatistic
   * const storeStatistic = await prisma.storeStatistic.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends StoreStatisticFindFirstArgs>(args?: Prisma.SelectSubset<T, StoreStatisticFindFirstArgs<ExtArgs>>): Prisma.Prisma__StoreStatisticClient<runtime.Types.Result.GetResult<Prisma.$StoreStatisticPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first StoreStatistic that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StoreStatisticFindFirstOrThrowArgs} args - Arguments to find a StoreStatistic
   * @example
   * // Get one StoreStatistic
   * const storeStatistic = await prisma.storeStatistic.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends StoreStatisticFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, StoreStatisticFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__StoreStatisticClient<runtime.Types.Result.GetResult<Prisma.$StoreStatisticPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more StoreStatistics that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StoreStatisticFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all StoreStatistics
   * const storeStatistics = await prisma.storeStatistic.findMany()
   * 
   * // Get first 10 StoreStatistics
   * const storeStatistics = await prisma.storeStatistic.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const storeStatisticWithIdOnly = await prisma.storeStatistic.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends StoreStatisticFindManyArgs>(args?: Prisma.SelectSubset<T, StoreStatisticFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$StoreStatisticPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a StoreStatistic.
   * @param {StoreStatisticCreateArgs} args - Arguments to create a StoreStatistic.
   * @example
   * // Create one StoreStatistic
   * const StoreStatistic = await prisma.storeStatistic.create({
   *   data: {
   *     // ... data to create a StoreStatistic
   *   }
   * })
   * 
   */
  create<T extends StoreStatisticCreateArgs>(args: Prisma.SelectSubset<T, StoreStatisticCreateArgs<ExtArgs>>): Prisma.Prisma__StoreStatisticClient<runtime.Types.Result.GetResult<Prisma.$StoreStatisticPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many StoreStatistics.
   * @param {StoreStatisticCreateManyArgs} args - Arguments to create many StoreStatistics.
   * @example
   * // Create many StoreStatistics
   * const storeStatistic = await prisma.storeStatistic.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends StoreStatisticCreateManyArgs>(args?: Prisma.SelectSubset<T, StoreStatisticCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many StoreStatistics and returns the data saved in the database.
   * @param {StoreStatisticCreateManyAndReturnArgs} args - Arguments to create many StoreStatistics.
   * @example
   * // Create many StoreStatistics
   * const storeStatistic = await prisma.storeStatistic.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many StoreStatistics and only return the `id`
   * const storeStatisticWithIdOnly = await prisma.storeStatistic.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends StoreStatisticCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, StoreStatisticCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$StoreStatisticPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a StoreStatistic.
   * @param {StoreStatisticDeleteArgs} args - Arguments to delete one StoreStatistic.
   * @example
   * // Delete one StoreStatistic
   * const StoreStatistic = await prisma.storeStatistic.delete({
   *   where: {
   *     // ... filter to delete one StoreStatistic
   *   }
   * })
   * 
   */
  delete<T extends StoreStatisticDeleteArgs>(args: Prisma.SelectSubset<T, StoreStatisticDeleteArgs<ExtArgs>>): Prisma.Prisma__StoreStatisticClient<runtime.Types.Result.GetResult<Prisma.$StoreStatisticPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one StoreStatistic.
   * @param {StoreStatisticUpdateArgs} args - Arguments to update one StoreStatistic.
   * @example
   * // Update one StoreStatistic
   * const storeStatistic = await prisma.storeStatistic.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends StoreStatisticUpdateArgs>(args: Prisma.SelectSubset<T, StoreStatisticUpdateArgs<ExtArgs>>): Prisma.Prisma__StoreStatisticClient<runtime.Types.Result.GetResult<Prisma.$StoreStatisticPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more StoreStatistics.
   * @param {StoreStatisticDeleteManyArgs} args - Arguments to filter StoreStatistics to delete.
   * @example
   * // Delete a few StoreStatistics
   * const { count } = await prisma.storeStatistic.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends StoreStatisticDeleteManyArgs>(args?: Prisma.SelectSubset<T, StoreStatisticDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more StoreStatistics.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StoreStatisticUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many StoreStatistics
   * const storeStatistic = await prisma.storeStatistic.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends StoreStatisticUpdateManyArgs>(args: Prisma.SelectSubset<T, StoreStatisticUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more StoreStatistics and returns the data updated in the database.
   * @param {StoreStatisticUpdateManyAndReturnArgs} args - Arguments to update many StoreStatistics.
   * @example
   * // Update many StoreStatistics
   * const storeStatistic = await prisma.storeStatistic.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more StoreStatistics and only return the `id`
   * const storeStatisticWithIdOnly = await prisma.storeStatistic.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends StoreStatisticUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, StoreStatisticUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$StoreStatisticPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one StoreStatistic.
   * @param {StoreStatisticUpsertArgs} args - Arguments to update or create a StoreStatistic.
   * @example
   * // Update or create a StoreStatistic
   * const storeStatistic = await prisma.storeStatistic.upsert({
   *   create: {
   *     // ... data to create a StoreStatistic
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the StoreStatistic we want to update
   *   }
   * })
   */
  upsert<T extends StoreStatisticUpsertArgs>(args: Prisma.SelectSubset<T, StoreStatisticUpsertArgs<ExtArgs>>): Prisma.Prisma__StoreStatisticClient<runtime.Types.Result.GetResult<Prisma.$StoreStatisticPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of StoreStatistics.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StoreStatisticCountArgs} args - Arguments to filter StoreStatistics to count.
   * @example
   * // Count the number of StoreStatistics
   * const count = await prisma.storeStatistic.count({
   *   where: {
   *     // ... the filter for the StoreStatistics we want to count
   *   }
   * })
  **/
  count<T extends StoreStatisticCountArgs>(
    args?: Prisma.Subset<T, StoreStatisticCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], StoreStatisticCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a StoreStatistic.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StoreStatisticAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends StoreStatisticAggregateArgs>(args: Prisma.Subset<T, StoreStatisticAggregateArgs>): Prisma.PrismaPromise<GetStoreStatisticAggregateType<T>>

  /**
   * Group by StoreStatistic.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StoreStatisticGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends StoreStatisticGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: StoreStatisticGroupByArgs['orderBy'] }
      : { orderBy?: StoreStatisticGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, StoreStatisticGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetStoreStatisticGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the StoreStatistic model
 */
readonly fields: StoreStatisticFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for StoreStatistic.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__StoreStatisticClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  store<T extends Prisma.StoreDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.StoreDefaultArgs<ExtArgs>>): Prisma.Prisma__StoreClient<runtime.Types.Result.GetResult<Prisma.$StorePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the StoreStatistic model
 */
export interface StoreStatisticFieldRefs {
  readonly id: Prisma.FieldRef<"StoreStatistic", 'Int'>
  readonly storeId: Prisma.FieldRef<"StoreStatistic", 'Int'>
  readonly booksFound: Prisma.FieldRef<"StoreStatistic", 'Int'>
  readonly lastScrapedAt: Prisma.FieldRef<"StoreStatistic", 'DateTime'>
}
    

// Custom InputTypes
/**
 * StoreStatistic findUnique
 */
export type StoreStatisticFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StoreStatistic
   */
  select?: Prisma.StoreStatisticSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StoreStatistic
   */
  omit?: Prisma.StoreStatisticOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StoreStatisticInclude<ExtArgs> | null
  /**
   * Filter, which StoreStatistic to fetch.
   */
  where: Prisma.StoreStatisticWhereUniqueInput
}

/**
 * StoreStatistic findUniqueOrThrow
 */
export type StoreStatisticFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StoreStatistic
   */
  select?: Prisma.StoreStatisticSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StoreStatistic
   */
  omit?: Prisma.StoreStatisticOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StoreStatisticInclude<ExtArgs> | null
  /**
   * Filter, which StoreStatistic to fetch.
   */
  where: Prisma.StoreStatisticWhereUniqueInput
}

/**
 * StoreStatistic findFirst
 */
export type StoreStatisticFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StoreStatistic
   */
  select?: Prisma.StoreStatisticSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StoreStatistic
   */
  omit?: Prisma.StoreStatisticOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StoreStatisticInclude<ExtArgs> | null
  /**
   * Filter, which StoreStatistic to fetch.
   */
  where?: Prisma.StoreStatisticWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of StoreStatistics to fetch.
   */
  orderBy?: Prisma.StoreStatisticOrderByWithRelationInput | Prisma.StoreStatisticOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for StoreStatistics.
   */
  cursor?: Prisma.StoreStatisticWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` StoreStatistics from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` StoreStatistics.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of StoreStatistics.
   */
  distinct?: Prisma.StoreStatisticScalarFieldEnum | Prisma.StoreStatisticScalarFieldEnum[]
}

/**
 * StoreStatistic findFirstOrThrow
 */
export type StoreStatisticFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StoreStatistic
   */
  select?: Prisma.StoreStatisticSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StoreStatistic
   */
  omit?: Prisma.StoreStatisticOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StoreStatisticInclude<ExtArgs> | null
  /**
   * Filter, which StoreStatistic to fetch.
   */
  where?: Prisma.StoreStatisticWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of StoreStatistics to fetch.
   */
  orderBy?: Prisma.StoreStatisticOrderByWithRelationInput | Prisma.StoreStatisticOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for StoreStatistics.
   */
  cursor?: Prisma.StoreStatisticWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` StoreStatistics from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` StoreStatistics.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of StoreStatistics.
   */
  distinct?: Prisma.StoreStatisticScalarFieldEnum | Prisma.StoreStatisticScalarFieldEnum[]
}

/**
 * StoreStatistic findMany
 */
export type StoreStatisticFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StoreStatistic
   */
  select?: Prisma.StoreStatisticSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StoreStatistic
   */
  omit?: Prisma.StoreStatisticOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StoreStatisticInclude<ExtArgs> | null
  /**
   * Filter, which StoreStatistics to fetch.
   */
  where?: Prisma.StoreStatisticWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of StoreStatistics to fetch.
   */
  orderBy?: Prisma.StoreStatisticOrderByWithRelationInput | Prisma.StoreStatisticOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing StoreStatistics.
   */
  cursor?: Prisma.StoreStatisticWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` StoreStatistics from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` StoreStatistics.
   */
  skip?: number
  distinct?: Prisma.StoreStatisticScalarFieldEnum | Prisma.StoreStatisticScalarFieldEnum[]
}

/**
 * StoreStatistic create
 */
export type StoreStatisticCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StoreStatistic
   */
  select?: Prisma.StoreStatisticSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StoreStatistic
   */
  omit?: Prisma.StoreStatisticOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StoreStatisticInclude<ExtArgs> | null
  /**
   * The data needed to create a StoreStatistic.
   */
  data: Prisma.XOR<Prisma.StoreStatisticCreateInput, Prisma.StoreStatisticUncheckedCreateInput>
}

/**
 * StoreStatistic createMany
 */
export type StoreStatisticCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many StoreStatistics.
   */
  data: Prisma.StoreStatisticCreateManyInput | Prisma.StoreStatisticCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * StoreStatistic createManyAndReturn
 */
export type StoreStatisticCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StoreStatistic
   */
  select?: Prisma.StoreStatisticSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the StoreStatistic
   */
  omit?: Prisma.StoreStatisticOmit<ExtArgs> | null
  /**
   * The data used to create many StoreStatistics.
   */
  data: Prisma.StoreStatisticCreateManyInput | Prisma.StoreStatisticCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StoreStatisticIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * StoreStatistic update
 */
export type StoreStatisticUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StoreStatistic
   */
  select?: Prisma.StoreStatisticSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StoreStatistic
   */
  omit?: Prisma.StoreStatisticOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StoreStatisticInclude<ExtArgs> | null
  /**
   * The data needed to update a StoreStatistic.
   */
  data: Prisma.XOR<Prisma.StoreStatisticUpdateInput, Prisma.StoreStatisticUncheckedUpdateInput>
  /**
   * Choose, which StoreStatistic to update.
   */
  where: Prisma.StoreStatisticWhereUniqueInput
}

/**
 * StoreStatistic updateMany
 */
export type StoreStatisticUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update StoreStatistics.
   */
  data: Prisma.XOR<Prisma.StoreStatisticUpdateManyMutationInput, Prisma.StoreStatisticUncheckedUpdateManyInput>
  /**
   * Filter which StoreStatistics to update
   */
  where?: Prisma.StoreStatisticWhereInput
  /**
   * Limit how many StoreStatistics to update.
   */
  limit?: number
}

/**
 * StoreStatistic updateManyAndReturn
 */
export type StoreStatisticUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StoreStatistic
   */
  select?: Prisma.StoreStatisticSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the StoreStatistic
   */
  omit?: Prisma.StoreStatisticOmit<ExtArgs> | null
  /**
   * The data used to update StoreStatistics.
   */
  data: Prisma.XOR<Prisma.StoreStatisticUpdateManyMutationInput, Prisma.StoreStatisticUncheckedUpdateManyInput>
  /**
   * Filter which StoreStatistics to update
   */
  where?: Prisma.StoreStatisticWhereInput
  /**
   * Limit how many StoreStatistics to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StoreStatisticIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * StoreStatistic upsert
 */
export type StoreStatisticUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StoreStatistic
   */
  select?: Prisma.StoreStatisticSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StoreStatistic
   */
  omit?: Prisma.StoreStatisticOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StoreStatisticInclude<ExtArgs> | null
  /**
   * The filter to search for the StoreStatistic to update in case it exists.
   */
  where: Prisma.StoreStatisticWhereUniqueInput
  /**
   * In case the StoreStatistic found by the `where` argument doesn't exist, create a new StoreStatistic with this data.
   */
  create: Prisma.XOR<Prisma.StoreStatisticCreateInput, Prisma.StoreStatisticUncheckedCreateInput>
  /**
   * In case the StoreStatistic was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.StoreStatisticUpdateInput, Prisma.StoreStatisticUncheckedUpdateInput>
}

/**
 * StoreStatistic delete
 */
export type StoreStatisticDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StoreStatistic
   */
  select?: Prisma.StoreStatisticSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StoreStatistic
   */
  omit?: Prisma.StoreStatisticOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StoreStatisticInclude<ExtArgs> | null
  /**
   * Filter which StoreStatistic to delete.
   */
  where: Prisma.StoreStatisticWhereUniqueInput
}

/**
 * StoreStatistic deleteMany
 */
export type StoreStatisticDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which StoreStatistics to delete
   */
  where?: Prisma.StoreStatisticWhereInput
  /**
   * Limit how many StoreStatistics to delete.
   */
  limit?: number
}

/**
 * StoreStatistic without action
 */
export type StoreStatisticDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StoreStatistic
   */
  select?: Prisma.StoreStatisticSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StoreStatistic
   */
  omit?: Prisma.StoreStatisticOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StoreStatisticInclude<ExtArgs> | null
}
