
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `ViewedBook` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model ViewedBook
 * 
 */
export type ViewedBookModel = runtime.Types.Result.DefaultSelection<Prisma.$ViewedBookPayload>

export type AggregateViewedBook = {
  _count: ViewedBookCountAggregateOutputType | null
  _avg: ViewedBookAvgAggregateOutputType | null
  _sum: ViewedBookSumAggregateOutputType | null
  _min: ViewedBookMinAggregateOutputType | null
  _max: ViewedBookMaxAggregateOutputType | null
}

export type ViewedBookAvgAggregateOutputType = {
  id: number | null
  searchLogId: number | null
  bookId: number | null
  similarity: number | null
}

export type ViewedBookSumAggregateOutputType = {
  id: number | null
  searchLogId: number | null
  bookId: number | null
  similarity: number | null
}

export type ViewedBookMinAggregateOutputType = {
  id: number | null
  searchLogId: number | null
  bookId: number | null
  bookLink: string | null
  viewedAt: Date | null
  similarity: number | null
}

export type ViewedBookMaxAggregateOutputType = {
  id: number | null
  searchLogId: number | null
  bookId: number | null
  bookLink: string | null
  viewedAt: Date | null
  similarity: number | null
}

export type ViewedBookCountAggregateOutputType = {
  id: number
  searchLogId: number
  bookId: number
  bookLink: number
  viewedAt: number
  similarity: number
  _all: number
}


export type ViewedBookAvgAggregateInputType = {
  id?: true
  searchLogId?: true
  bookId?: true
  similarity?: true
}

export type ViewedBookSumAggregateInputType = {
  id?: true
  searchLogId?: true
  bookId?: true
  similarity?: true
}

export type ViewedBookMinAggregateInputType = {
  id?: true
  searchLogId?: true
  bookId?: true
  bookLink?: true
  viewedAt?: true
  similarity?: true
}

export type ViewedBookMaxAggregateInputType = {
  id?: true
  searchLogId?: true
  bookId?: true
  bookLink?: true
  viewedAt?: true
  similarity?: true
}

export type ViewedBookCountAggregateInputType = {
  id?: true
  searchLogId?: true
  bookId?: true
  bookLink?: true
  viewedAt?: true
  similarity?: true
  _all?: true
}

export type ViewedBookAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ViewedBook to aggregate.
   */
  where?: Prisma.ViewedBookWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ViewedBooks to fetch.
   */
  orderBy?: Prisma.ViewedBookOrderByWithRelationInput | Prisma.ViewedBookOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ViewedBookWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ViewedBooks from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ViewedBooks.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned ViewedBooks
  **/
  _count?: true | ViewedBookCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: ViewedBookAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: ViewedBookSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ViewedBookMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ViewedBookMaxAggregateInputType
}

export type GetViewedBookAggregateType<T extends ViewedBookAggregateArgs> = {
      [P in keyof T & keyof AggregateViewedBook]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateViewedBook[P]>
    : Prisma.GetScalarType<T[P], AggregateViewedBook[P]>
}




export type ViewedBookGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ViewedBookWhereInput
  orderBy?: Prisma.ViewedBookOrderByWithAggregationInput | Prisma.ViewedBookOrderByWithAggregationInput[]
  by: Prisma.ViewedBookScalarFieldEnum[] | Prisma.ViewedBookScalarFieldEnum
  having?: Prisma.ViewedBookScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ViewedBookCountAggregateInputType | true
  _avg?: ViewedBookAvgAggregateInputType
  _sum?: ViewedBookSumAggregateInputType
  _min?: ViewedBookMinAggregateInputType
  _max?: ViewedBookMaxAggregateInputType
}

export type ViewedBookGroupByOutputType = {
  id: number
  searchLogId: number
  bookId: number | null
  bookLink: string
  viewedAt: Date
  similarity: number
  _count: ViewedBookCountAggregateOutputType | null
  _avg: ViewedBookAvgAggregateOutputType | null
  _sum: ViewedBookSumAggregateOutputType | null
  _min: ViewedBookMinAggregateOutputType | null
  _max: ViewedBookMaxAggregateOutputType | null
}

type GetViewedBookGroupByPayload<T extends ViewedBookGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ViewedBookGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ViewedBookGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ViewedBookGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ViewedBookGroupByOutputType[P]>
      }
    >
  >



export type ViewedBookWhereInput = {
  AND?: Prisma.ViewedBookWhereInput | Prisma.ViewedBookWhereInput[]
  OR?: Prisma.ViewedBookWhereInput[]
  NOT?: Prisma.ViewedBookWhereInput | Prisma.ViewedBookWhereInput[]
  id?: Prisma.IntFilter<"ViewedBook"> | number
  searchLogId?: Prisma.IntFilter<"ViewedBook"> | number
  bookId?: Prisma.IntNullableFilter<"ViewedBook"> | number | null
  bookLink?: Prisma.StringFilter<"ViewedBook"> | string
  viewedAt?: Prisma.DateTimeFilter<"ViewedBook"> | Date | string
  similarity?: Prisma.FloatFilter<"ViewedBook"> | number
  searchLog?: Prisma.XOR<Prisma.SearchLogScalarRelationFilter, Prisma.SearchLogWhereInput>
  book?: Prisma.XOR<Prisma.BookNullableScalarRelationFilter, Prisma.BookWhereInput> | null
}

export type ViewedBookOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  searchLogId?: Prisma.SortOrder
  bookId?: Prisma.SortOrderInput | Prisma.SortOrder
  bookLink?: Prisma.SortOrder
  viewedAt?: Prisma.SortOrder
  similarity?: Prisma.SortOrder
  searchLog?: Prisma.SearchLogOrderByWithRelationInput
  book?: Prisma.BookOrderByWithRelationInput
}

export type ViewedBookWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.ViewedBookWhereInput | Prisma.ViewedBookWhereInput[]
  OR?: Prisma.ViewedBookWhereInput[]
  NOT?: Prisma.ViewedBookWhereInput | Prisma.ViewedBookWhereInput[]
  searchLogId?: Prisma.IntFilter<"ViewedBook"> | number
  bookId?: Prisma.IntNullableFilter<"ViewedBook"> | number | null
  bookLink?: Prisma.StringFilter<"ViewedBook"> | string
  viewedAt?: Prisma.DateTimeFilter<"ViewedBook"> | Date | string
  similarity?: Prisma.FloatFilter<"ViewedBook"> | number
  searchLog?: Prisma.XOR<Prisma.SearchLogScalarRelationFilter, Prisma.SearchLogWhereInput>
  book?: Prisma.XOR<Prisma.BookNullableScalarRelationFilter, Prisma.BookWhereInput> | null
}, "id">

export type ViewedBookOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  searchLogId?: Prisma.SortOrder
  bookId?: Prisma.SortOrderInput | Prisma.SortOrder
  bookLink?: Prisma.SortOrder
  viewedAt?: Prisma.SortOrder
  similarity?: Prisma.SortOrder
  _count?: Prisma.ViewedBookCountOrderByAggregateInput
  _avg?: Prisma.ViewedBookAvgOrderByAggregateInput
  _max?: Prisma.ViewedBookMaxOrderByAggregateInput
  _min?: Prisma.ViewedBookMinOrderByAggregateInput
  _sum?: Prisma.ViewedBookSumOrderByAggregateInput
}

export type ViewedBookScalarWhereWithAggregatesInput = {
  AND?: Prisma.ViewedBookScalarWhereWithAggregatesInput | Prisma.ViewedBookScalarWhereWithAggregatesInput[]
  OR?: Prisma.ViewedBookScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ViewedBookScalarWhereWithAggregatesInput | Prisma.ViewedBookScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"ViewedBook"> | number
  searchLogId?: Prisma.IntWithAggregatesFilter<"ViewedBook"> | number
  bookId?: Prisma.IntNullableWithAggregatesFilter<"ViewedBook"> | number | null
  bookLink?: Prisma.StringWithAggregatesFilter<"ViewedBook"> | string
  viewedAt?: Prisma.DateTimeWithAggregatesFilter<"ViewedBook"> | Date | string
  similarity?: Prisma.FloatWithAggregatesFilter<"ViewedBook"> | number
}

export type ViewedBookCreateInput = {
  bookLink: string
  viewedAt?: Date | string
  similarity: number
  searchLog: Prisma.SearchLogCreateNestedOneWithoutViewedBooksInput
  book?: Prisma.BookCreateNestedOneWithoutViewedBooksInput
}

export type ViewedBookUncheckedCreateInput = {
  id?: number
  searchLogId: number
  bookId?: number | null
  bookLink: string
  viewedAt?: Date | string
  similarity: number
}

export type ViewedBookUpdateInput = {
  bookLink?: Prisma.StringFieldUpdateOperationsInput | string
  viewedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  similarity?: Prisma.FloatFieldUpdateOperationsInput | number
  searchLog?: Prisma.SearchLogUpdateOneRequiredWithoutViewedBooksNestedInput
  book?: Prisma.BookUpdateOneWithoutViewedBooksNestedInput
}

export type ViewedBookUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  searchLogId?: Prisma.IntFieldUpdateOperationsInput | number
  bookId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  bookLink?: Prisma.StringFieldUpdateOperationsInput | string
  viewedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  similarity?: Prisma.FloatFieldUpdateOperationsInput | number
}

export type ViewedBookCreateManyInput = {
  id?: number
  searchLogId: number
  bookId?: number | null
  bookLink: string
  viewedAt?: Date | string
  similarity: number
}

export type ViewedBookUpdateManyMutationInput = {
  bookLink?: Prisma.StringFieldUpdateOperationsInput | string
  viewedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  similarity?: Prisma.FloatFieldUpdateOperationsInput | number
}

export type ViewedBookUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  searchLogId?: Prisma.IntFieldUpdateOperationsInput | number
  bookId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  bookLink?: Prisma.StringFieldUpdateOperationsInput | string
  viewedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  similarity?: Prisma.FloatFieldUpdateOperationsInput | number
}

export type ViewedBookListRelationFilter = {
  every?: Prisma.ViewedBookWhereInput
  some?: Prisma.ViewedBookWhereInput
  none?: Prisma.ViewedBookWhereInput
}

export type ViewedBookOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type ViewedBookCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  searchLogId?: Prisma.SortOrder
  bookId?: Prisma.SortOrder
  bookLink?: Prisma.SortOrder
  viewedAt?: Prisma.SortOrder
  similarity?: Prisma.SortOrder
}

export type ViewedBookAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  searchLogId?: Prisma.SortOrder
  bookId?: Prisma.SortOrder
  similarity?: Prisma.SortOrder
}

export type ViewedBookMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  searchLogId?: Prisma.SortOrder
  bookId?: Prisma.SortOrder
  bookLink?: Prisma.SortOrder
  viewedAt?: Prisma.SortOrder
  similarity?: Prisma.SortOrder
}

export type ViewedBookMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  searchLogId?: Prisma.SortOrder
  bookId?: Prisma.SortOrder
  bookLink?: Prisma.SortOrder
  viewedAt?: Prisma.SortOrder
  similarity?: Prisma.SortOrder
}

export type ViewedBookSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  searchLogId?: Prisma.SortOrder
  bookId?: Prisma.SortOrder
  similarity?: Prisma.SortOrder
}

export type ViewedBookCreateNestedManyWithoutBookInput = {
  create?: Prisma.XOR<Prisma.ViewedBookCreateWithoutBookInput, Prisma.ViewedBookUncheckedCreateWithoutBookInput> | Prisma.ViewedBookCreateWithoutBookInput[] | Prisma.ViewedBookUncheckedCreateWithoutBookInput[]
  connectOrCreate?: Prisma.ViewedBookCreateOrConnectWithoutBookInput | Prisma.ViewedBookCreateOrConnectWithoutBookInput[]
  createMany?: Prisma.ViewedBookCreateManyBookInputEnvelope
  connect?: Prisma.ViewedBookWhereUniqueInput | Prisma.ViewedBookWhereUniqueInput[]
}

export type ViewedBookUncheckedCreateNestedManyWithoutBookInput = {
  create?: Prisma.XOR<Prisma.ViewedBookCreateWithoutBookInput, Prisma.ViewedBookUncheckedCreateWithoutBookInput> | Prisma.ViewedBookCreateWithoutBookInput[] | Prisma.ViewedBookUncheckedCreateWithoutBookInput[]
  connectOrCreate?: Prisma.ViewedBookCreateOrConnectWithoutBookInput | Prisma.ViewedBookCreateOrConnectWithoutBookInput[]
  createMany?: Prisma.ViewedBookCreateManyBookInputEnvelope
  connect?: Prisma.ViewedBookWhereUniqueInput | Prisma.ViewedBookWhereUniqueInput[]
}

export type ViewedBookUpdateManyWithoutBookNestedInput = {
  create?: Prisma.XOR<Prisma.ViewedBookCreateWithoutBookInput, Prisma.ViewedBookUncheckedCreateWithoutBookInput> | Prisma.ViewedBookCreateWithoutBookInput[] | Prisma.ViewedBookUncheckedCreateWithoutBookInput[]
  connectOrCreate?: Prisma.ViewedBookCreateOrConnectWithoutBookInput | Prisma.ViewedBookCreateOrConnectWithoutBookInput[]
  upsert?: Prisma.ViewedBookUpsertWithWhereUniqueWithoutBookInput | Prisma.ViewedBookUpsertWithWhereUniqueWithoutBookInput[]
  createMany?: Prisma.ViewedBookCreateManyBookInputEnvelope
  set?: Prisma.ViewedBookWhereUniqueInput | Prisma.ViewedBookWhereUniqueInput[]
  disconnect?: Prisma.ViewedBookWhereUniqueInput | Prisma.ViewedBookWhereUniqueInput[]
  delete?: Prisma.ViewedBookWhereUniqueInput | Prisma.ViewedBookWhereUniqueInput[]
  connect?: Prisma.ViewedBookWhereUniqueInput | Prisma.ViewedBookWhereUniqueInput[]
  update?: Prisma.ViewedBookUpdateWithWhereUniqueWithoutBookInput | Prisma.ViewedBookUpdateWithWhereUniqueWithoutBookInput[]
  updateMany?: Prisma.ViewedBookUpdateManyWithWhereWithoutBookInput | Prisma.ViewedBookUpdateManyWithWhereWithoutBookInput[]
  deleteMany?: Prisma.ViewedBookScalarWhereInput | Prisma.ViewedBookScalarWhereInput[]
}

export type ViewedBookUncheckedUpdateManyWithoutBookNestedInput = {
  create?: Prisma.XOR<Prisma.ViewedBookCreateWithoutBookInput, Prisma.ViewedBookUncheckedCreateWithoutBookInput> | Prisma.ViewedBookCreateWithoutBookInput[] | Prisma.ViewedBookUncheckedCreateWithoutBookInput[]
  connectOrCreate?: Prisma.ViewedBookCreateOrConnectWithoutBookInput | Prisma.ViewedBookCreateOrConnectWithoutBookInput[]
  upsert?: Prisma.ViewedBookUpsertWithWhereUniqueWithoutBookInput | Prisma.ViewedBookUpsertWithWhereUniqueWithoutBookInput[]
  createMany?: Prisma.ViewedBookCreateManyBookInputEnvelope
  set?: Prisma.ViewedBookWhereUniqueInput | Prisma.ViewedBookWhereUniqueInput[]
  disconnect?: Prisma.ViewedBookWhereUniqueInput | Prisma.ViewedBookWhereUniqueInput[]
  delete?: Prisma.ViewedBookWhereUniqueInput | Prisma.ViewedBookWhereUniqueInput[]
  connect?: Prisma.ViewedBookWhereUniqueInput | Prisma.ViewedBookWhereUniqueInput[]
  update?: Prisma.ViewedBookUpdateWithWhereUniqueWithoutBookInput | Prisma.ViewedBookUpdateWithWhereUniqueWithoutBookInput[]
  updateMany?: Prisma.ViewedBookUpdateManyWithWhereWithoutBookInput | Prisma.ViewedBookUpdateManyWithWhereWithoutBookInput[]
  deleteMany?: Prisma.ViewedBookScalarWhereInput | Prisma.ViewedBookScalarWhereInput[]
}

export type ViewedBookCreateNestedManyWithoutSearchLogInput = {
  create?: Prisma.XOR<Prisma.ViewedBookCreateWithoutSearchLogInput, Prisma.ViewedBookUncheckedCreateWithoutSearchLogInput> | Prisma.ViewedBookCreateWithoutSearchLogInput[] | Prisma.ViewedBookUncheckedCreateWithoutSearchLogInput[]
  connectOrCreate?: Prisma.ViewedBookCreateOrConnectWithoutSearchLogInput | Prisma.ViewedBookCreateOrConnectWithoutSearchLogInput[]
  createMany?: Prisma.ViewedBookCreateManySearchLogInputEnvelope
  connect?: Prisma.ViewedBookWhereUniqueInput | Prisma.ViewedBookWhereUniqueInput[]
}

export type ViewedBookUncheckedCreateNestedManyWithoutSearchLogInput = {
  create?: Prisma.XOR<Prisma.ViewedBookCreateWithoutSearchLogInput, Prisma.ViewedBookUncheckedCreateWithoutSearchLogInput> | Prisma.ViewedBookCreateWithoutSearchLogInput[] | Prisma.ViewedBookUncheckedCreateWithoutSearchLogInput[]
  connectOrCreate?: Prisma.ViewedBookCreateOrConnectWithoutSearchLogInput | Prisma.ViewedBookCreateOrConnectWithoutSearchLogInput[]
  createMany?: Prisma.ViewedBookCreateManySearchLogInputEnvelope
  connect?: Prisma.ViewedBookWhereUniqueInput | Prisma.ViewedBookWhereUniqueInput[]
}

export type ViewedBookUpdateManyWithoutSearchLogNestedInput = {
  create?: Prisma.XOR<Prisma.ViewedBookCreateWithoutSearchLogInput, Prisma.ViewedBookUncheckedCreateWithoutSearchLogInput> | Prisma.ViewedBookCreateWithoutSearchLogInput[] | Prisma.ViewedBookUncheckedCreateWithoutSearchLogInput[]
  connectOrCreate?: Prisma.ViewedBookCreateOrConnectWithoutSearchLogInput | Prisma.ViewedBookCreateOrConnectWithoutSearchLogInput[]
  upsert?: Prisma.ViewedBookUpsertWithWhereUniqueWithoutSearchLogInput | Prisma.ViewedBookUpsertWithWhereUniqueWithoutSearchLogInput[]
  createMany?: Prisma.ViewedBookCreateManySearchLogInputEnvelope
  set?: Prisma.ViewedBookWhereUniqueInput | Prisma.ViewedBookWhereUniqueInput[]
  disconnect?: Prisma.ViewedBookWhereUniqueInput | Prisma.ViewedBookWhereUniqueInput[]
  delete?: Prisma.ViewedBookWhereUniqueInput | Prisma.ViewedBookWhereUniqueInput[]
  connect?: Prisma.ViewedBookWhereUniqueInput | Prisma.ViewedBookWhereUniqueInput[]
  update?: Prisma.ViewedBookUpdateWithWhereUniqueWithoutSearchLogInput | Prisma.ViewedBookUpdateWithWhereUniqueWithoutSearchLogInput[]
  updateMany?: Prisma.ViewedBookUpdateManyWithWhereWithoutSearchLogInput | Prisma.ViewedBookUpdateManyWithWhereWithoutSearchLogInput[]
  deleteMany?: Prisma.ViewedBookScalarWhereInput | Prisma.ViewedBookScalarWhereInput[]
}

export type ViewedBookUncheckedUpdateManyWithoutSearchLogNestedInput = {
  create?: Prisma.XOR<Prisma.ViewedBookCreateWithoutSearchLogInput, Prisma.ViewedBookUncheckedCreateWithoutSearchLogInput> | Prisma.ViewedBookCreateWithoutSearchLogInput[] | Prisma.ViewedBookUncheckedCreateWithoutSearchLogInput[]
  connectOrCreate?: Prisma.ViewedBookCreateOrConnectWithoutSearchLogInput | Prisma.ViewedBookCreateOrConnectWithoutSearchLogInput[]
  upsert?: Prisma.ViewedBookUpsertWithWhereUniqueWithoutSearchLogInput | Prisma.ViewedBookUpsertWithWhereUniqueWithoutSearchLogInput[]
  createMany?: Prisma.ViewedBookCreateManySearchLogInputEnvelope
  set?: Prisma.ViewedBookWhereUniqueInput | Prisma.ViewedBookWhereUniqueInput[]
  disconnect?: Prisma.ViewedBookWhereUniqueInput | Prisma.ViewedBookWhereUniqueInput[]
  delete?: Prisma.ViewedBookWhereUniqueInput | Prisma.ViewedBookWhereUniqueInput[]
  connect?: Prisma.ViewedBookWhereUniqueInput | Prisma.ViewedBookWhereUniqueInput[]
  update?: Prisma.ViewedBookUpdateWithWhereUniqueWithoutSearchLogInput | Prisma.ViewedBookUpdateWithWhereUniqueWithoutSearchLogInput[]
  updateMany?: Prisma.ViewedBookUpdateManyWithWhereWithoutSearchLogInput | Prisma.ViewedBookUpdateManyWithWhereWithoutSearchLogInput[]
  deleteMany?: Prisma.ViewedBookScalarWhereInput | Prisma.ViewedBookScalarWhereInput[]
}

export type ViewedBookCreateWithoutBookInput = {
  bookLink: string
  viewedAt?: Date | string
  similarity: number
  searchLog: Prisma.SearchLogCreateNestedOneWithoutViewedBooksInput
}

export type ViewedBookUncheckedCreateWithoutBookInput = {
  id?: number
  searchLogId: number
  bookLink: string
  viewedAt?: Date | string
  similarity: number
}

export type ViewedBookCreateOrConnectWithoutBookInput = {
  where: Prisma.ViewedBookWhereUniqueInput
  create: Prisma.XOR<Prisma.ViewedBookCreateWithoutBookInput, Prisma.ViewedBookUncheckedCreateWithoutBookInput>
}

export type ViewedBookCreateManyBookInputEnvelope = {
  data: Prisma.ViewedBookCreateManyBookInput | Prisma.ViewedBookCreateManyBookInput[]
  skipDuplicates?: boolean
}

export type ViewedBookUpsertWithWhereUniqueWithoutBookInput = {
  where: Prisma.ViewedBookWhereUniqueInput
  update: Prisma.XOR<Prisma.ViewedBookUpdateWithoutBookInput, Prisma.ViewedBookUncheckedUpdateWithoutBookInput>
  create: Prisma.XOR<Prisma.ViewedBookCreateWithoutBookInput, Prisma.ViewedBookUncheckedCreateWithoutBookInput>
}

export type ViewedBookUpdateWithWhereUniqueWithoutBookInput = {
  where: Prisma.ViewedBookWhereUniqueInput
  data: Prisma.XOR<Prisma.ViewedBookUpdateWithoutBookInput, Prisma.ViewedBookUncheckedUpdateWithoutBookInput>
}

export type ViewedBookUpdateManyWithWhereWithoutBookInput = {
  where: Prisma.ViewedBookScalarWhereInput
  data: Prisma.XOR<Prisma.ViewedBookUpdateManyMutationInput, Prisma.ViewedBookUncheckedUpdateManyWithoutBookInput>
}

export type ViewedBookScalarWhereInput = {
  AND?: Prisma.ViewedBookScalarWhereInput | Prisma.ViewedBookScalarWhereInput[]
  OR?: Prisma.ViewedBookScalarWhereInput[]
  NOT?: Prisma.ViewedBookScalarWhereInput | Prisma.ViewedBookScalarWhereInput[]
  id?: Prisma.IntFilter<"ViewedBook"> | number
  searchLogId?: Prisma.IntFilter<"ViewedBook"> | number
  bookId?: Prisma.IntNullableFilter<"ViewedBook"> | number | null
  bookLink?: Prisma.StringFilter<"ViewedBook"> | string
  viewedAt?: Prisma.DateTimeFilter<"ViewedBook"> | Date | string
  similarity?: Prisma.FloatFilter<"ViewedBook"> | number
}

export type ViewedBookCreateWithoutSearchLogInput = {
  bookLink: string
  viewedAt?: Date | string
  similarity: number
  book?: Prisma.BookCreateNestedOneWithoutViewedBooksInput
}

export type ViewedBookUncheckedCreateWithoutSearchLogInput = {
  id?: number
  bookId?: number | null
  bookLink: string
  viewedAt?: Date | string
  similarity: number
}

export type ViewedBookCreateOrConnectWithoutSearchLogInput = {
  where: Prisma.ViewedBookWhereUniqueInput
  create: Prisma.XOR<Prisma.ViewedBookCreateWithoutSearchLogInput, Prisma.ViewedBookUncheckedCreateWithoutSearchLogInput>
}

export type ViewedBookCreateManySearchLogInputEnvelope = {
  data: Prisma.ViewedBookCreateManySearchLogInput | Prisma.ViewedBookCreateManySearchLogInput[]
  skipDuplicates?: boolean
}

export type ViewedBookUpsertWithWhereUniqueWithoutSearchLogInput = {
  where: Prisma.ViewedBookWhereUniqueInput
  update: Prisma.XOR<Prisma.ViewedBookUpdateWithoutSearchLogInput, Prisma.ViewedBookUncheckedUpdateWithoutSearchLogInput>
  create: Prisma.XOR<Prisma.ViewedBookCreateWithoutSearchLogInput, Prisma.ViewedBookUncheckedCreateWithoutSearchLogInput>
}

export type ViewedBookUpdateWithWhereUniqueWithoutSearchLogInput = {
  where: Prisma.ViewedBookWhereUniqueInput
  data: Prisma.XOR<Prisma.ViewedBookUpdateWithoutSearchLogInput, Prisma.ViewedBookUncheckedUpdateWithoutSearchLogInput>
}

export type ViewedBookUpdateManyWithWhereWithoutSearchLogInput = {
  where: Prisma.ViewedBookScalarWhereInput
  data: Prisma.XOR<Prisma.ViewedBookUpdateManyMutationInput, Prisma.ViewedBookUncheckedUpdateManyWithoutSearchLogInput>
}

export type ViewedBookCreateManyBookInput = {
  id?: number
  searchLogId: number
  bookLink: string
  viewedAt?: Date | string
  similarity: number
}

export type ViewedBookUpdateWithoutBookInput = {
  bookLink?: Prisma.StringFieldUpdateOperationsInput | string
  viewedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  similarity?: Prisma.FloatFieldUpdateOperationsInput | number
  searchLog?: Prisma.SearchLogUpdateOneRequiredWithoutViewedBooksNestedInput
}

export type ViewedBookUncheckedUpdateWithoutBookInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  searchLogId?: Prisma.IntFieldUpdateOperationsInput | number
  bookLink?: Prisma.StringFieldUpdateOperationsInput | string
  viewedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  similarity?: Prisma.FloatFieldUpdateOperationsInput | number
}

export type ViewedBookUncheckedUpdateManyWithoutBookInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  searchLogId?: Prisma.IntFieldUpdateOperationsInput | number
  bookLink?: Prisma.StringFieldUpdateOperationsInput | string
  viewedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  similarity?: Prisma.FloatFieldUpdateOperationsInput | number
}

export type ViewedBookCreateManySearchLogInput = {
  id?: number
  bookId?: number | null
  bookLink: string
  viewedAt?: Date | string
  similarity: number
}

export type ViewedBookUpdateWithoutSearchLogInput = {
  bookLink?: Prisma.StringFieldUpdateOperationsInput | string
  viewedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  similarity?: Prisma.FloatFieldUpdateOperationsInput | number
  book?: Prisma.BookUpdateOneWithoutViewedBooksNestedInput
}

export type ViewedBookUncheckedUpdateWithoutSearchLogInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  bookId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  bookLink?: Prisma.StringFieldUpdateOperationsInput | string
  viewedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  similarity?: Prisma.FloatFieldUpdateOperationsInput | number
}

export type ViewedBookUncheckedUpdateManyWithoutSearchLogInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  bookId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  bookLink?: Prisma.StringFieldUpdateOperationsInput | string
  viewedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  similarity?: Prisma.FloatFieldUpdateOperationsInput | number
}



export type ViewedBookSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  searchLogId?: boolean
  bookId?: boolean
  bookLink?: boolean
  viewedAt?: boolean
  similarity?: boolean
  searchLog?: boolean | Prisma.SearchLogDefaultArgs<ExtArgs>
  book?: boolean | Prisma.ViewedBook$bookArgs<ExtArgs>
}, ExtArgs["result"]["viewedBook"]>

export type ViewedBookSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  searchLogId?: boolean
  bookId?: boolean
  bookLink?: boolean
  viewedAt?: boolean
  similarity?: boolean
  searchLog?: boolean | Prisma.SearchLogDefaultArgs<ExtArgs>
  book?: boolean | Prisma.ViewedBook$bookArgs<ExtArgs>
}, ExtArgs["result"]["viewedBook"]>

export type ViewedBookSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  searchLogId?: boolean
  bookId?: boolean
  bookLink?: boolean
  viewedAt?: boolean
  similarity?: boolean
  searchLog?: boolean | Prisma.SearchLogDefaultArgs<ExtArgs>
  book?: boolean | Prisma.ViewedBook$bookArgs<ExtArgs>
}, ExtArgs["result"]["viewedBook"]>

export type ViewedBookSelectScalar = {
  id?: boolean
  searchLogId?: boolean
  bookId?: boolean
  bookLink?: boolean
  viewedAt?: boolean
  similarity?: boolean
}

export type ViewedBookOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "searchLogId" | "bookId" | "bookLink" | "viewedAt" | "similarity", ExtArgs["result"]["viewedBook"]>
export type ViewedBookInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  searchLog?: boolean | Prisma.SearchLogDefaultArgs<ExtArgs>
  book?: boolean | Prisma.ViewedBook$bookArgs<ExtArgs>
}
export type ViewedBookIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  searchLog?: boolean | Prisma.SearchLogDefaultArgs<ExtArgs>
  book?: boolean | Prisma.ViewedBook$bookArgs<ExtArgs>
}
export type ViewedBookIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  searchLog?: boolean | Prisma.SearchLogDefaultArgs<ExtArgs>
  book?: boolean | Prisma.ViewedBook$bookArgs<ExtArgs>
}

export type $ViewedBookPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "ViewedBook"
  objects: {
    searchLog: Prisma.$SearchLogPayload<ExtArgs>
    book: Prisma.$BookPayload<ExtArgs> | null
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    searchLogId: number
    bookId: number | null
    bookLink: string
    viewedAt: Date
    similarity: number
  }, ExtArgs["result"]["viewedBook"]>
  composites: {}
}

export type ViewedBookGetPayload<S extends boolean | null | undefined | ViewedBookDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ViewedBookPayload, S>

export type ViewedBookCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ViewedBookFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ViewedBookCountAggregateInputType | true
  }

export interface ViewedBookDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['ViewedBook'], meta: { name: 'ViewedBook' } }
  /**
   * Find zero or one ViewedBook that matches the filter.
   * @param {ViewedBookFindUniqueArgs} args - Arguments to find a ViewedBook
   * @example
   * // Get one ViewedBook
   * const viewedBook = await prisma.viewedBook.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ViewedBookFindUniqueArgs>(args: Prisma.SelectSubset<T, ViewedBookFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ViewedBookClient<runtime.Types.Result.GetResult<Prisma.$ViewedBookPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one ViewedBook that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ViewedBookFindUniqueOrThrowArgs} args - Arguments to find a ViewedBook
   * @example
   * // Get one ViewedBook
   * const viewedBook = await prisma.viewedBook.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ViewedBookFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ViewedBookFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ViewedBookClient<runtime.Types.Result.GetResult<Prisma.$ViewedBookPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ViewedBook that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ViewedBookFindFirstArgs} args - Arguments to find a ViewedBook
   * @example
   * // Get one ViewedBook
   * const viewedBook = await prisma.viewedBook.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ViewedBookFindFirstArgs>(args?: Prisma.SelectSubset<T, ViewedBookFindFirstArgs<ExtArgs>>): Prisma.Prisma__ViewedBookClient<runtime.Types.Result.GetResult<Prisma.$ViewedBookPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ViewedBook that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ViewedBookFindFirstOrThrowArgs} args - Arguments to find a ViewedBook
   * @example
   * // Get one ViewedBook
   * const viewedBook = await prisma.viewedBook.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ViewedBookFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ViewedBookFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ViewedBookClient<runtime.Types.Result.GetResult<Prisma.$ViewedBookPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more ViewedBooks that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ViewedBookFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all ViewedBooks
   * const viewedBooks = await prisma.viewedBook.findMany()
   * 
   * // Get first 10 ViewedBooks
   * const viewedBooks = await prisma.viewedBook.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const viewedBookWithIdOnly = await prisma.viewedBook.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ViewedBookFindManyArgs>(args?: Prisma.SelectSubset<T, ViewedBookFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ViewedBookPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a ViewedBook.
   * @param {ViewedBookCreateArgs} args - Arguments to create a ViewedBook.
   * @example
   * // Create one ViewedBook
   * const ViewedBook = await prisma.viewedBook.create({
   *   data: {
   *     // ... data to create a ViewedBook
   *   }
   * })
   * 
   */
  create<T extends ViewedBookCreateArgs>(args: Prisma.SelectSubset<T, ViewedBookCreateArgs<ExtArgs>>): Prisma.Prisma__ViewedBookClient<runtime.Types.Result.GetResult<Prisma.$ViewedBookPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many ViewedBooks.
   * @param {ViewedBookCreateManyArgs} args - Arguments to create many ViewedBooks.
   * @example
   * // Create many ViewedBooks
   * const viewedBook = await prisma.viewedBook.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ViewedBookCreateManyArgs>(args?: Prisma.SelectSubset<T, ViewedBookCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many ViewedBooks and returns the data saved in the database.
   * @param {ViewedBookCreateManyAndReturnArgs} args - Arguments to create many ViewedBooks.
   * @example
   * // Create many ViewedBooks
   * const viewedBook = await prisma.viewedBook.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many ViewedBooks and only return the `id`
   * const viewedBookWithIdOnly = await prisma.viewedBook.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ViewedBookCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ViewedBookCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ViewedBookPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a ViewedBook.
   * @param {ViewedBookDeleteArgs} args - Arguments to delete one ViewedBook.
   * @example
   * // Delete one ViewedBook
   * const ViewedBook = await prisma.viewedBook.delete({
   *   where: {
   *     // ... filter to delete one ViewedBook
   *   }
   * })
   * 
   */
  delete<T extends ViewedBookDeleteArgs>(args: Prisma.SelectSubset<T, ViewedBookDeleteArgs<ExtArgs>>): Prisma.Prisma__ViewedBookClient<runtime.Types.Result.GetResult<Prisma.$ViewedBookPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one ViewedBook.
   * @param {ViewedBookUpdateArgs} args - Arguments to update one ViewedBook.
   * @example
   * // Update one ViewedBook
   * const viewedBook = await prisma.viewedBook.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ViewedBookUpdateArgs>(args: Prisma.SelectSubset<T, ViewedBookUpdateArgs<ExtArgs>>): Prisma.Prisma__ViewedBookClient<runtime.Types.Result.GetResult<Prisma.$ViewedBookPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more ViewedBooks.
   * @param {ViewedBookDeleteManyArgs} args - Arguments to filter ViewedBooks to delete.
   * @example
   * // Delete a few ViewedBooks
   * const { count } = await prisma.viewedBook.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ViewedBookDeleteManyArgs>(args?: Prisma.SelectSubset<T, ViewedBookDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ViewedBooks.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ViewedBookUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many ViewedBooks
   * const viewedBook = await prisma.viewedBook.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ViewedBookUpdateManyArgs>(args: Prisma.SelectSubset<T, ViewedBookUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ViewedBooks and returns the data updated in the database.
   * @param {ViewedBookUpdateManyAndReturnArgs} args - Arguments to update many ViewedBooks.
   * @example
   * // Update many ViewedBooks
   * const viewedBook = await prisma.viewedBook.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more ViewedBooks and only return the `id`
   * const viewedBookWithIdOnly = await prisma.viewedBook.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ViewedBookUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ViewedBookUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ViewedBookPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one ViewedBook.
   * @param {ViewedBookUpsertArgs} args - Arguments to update or create a ViewedBook.
   * @example
   * // Update or create a ViewedBook
   * const viewedBook = await prisma.viewedBook.upsert({
   *   create: {
   *     // ... data to create a ViewedBook
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the ViewedBook we want to update
   *   }
   * })
   */
  upsert<T extends ViewedBookUpsertArgs>(args: Prisma.SelectSubset<T, ViewedBookUpsertArgs<ExtArgs>>): Prisma.Prisma__ViewedBookClient<runtime.Types.Result.GetResult<Prisma.$ViewedBookPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of ViewedBooks.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ViewedBookCountArgs} args - Arguments to filter ViewedBooks to count.
   * @example
   * // Count the number of ViewedBooks
   * const count = await prisma.viewedBook.count({
   *   where: {
   *     // ... the filter for the ViewedBooks we want to count
   *   }
   * })
  **/
  count<T extends ViewedBookCountArgs>(
    args?: Prisma.Subset<T, ViewedBookCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ViewedBookCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a ViewedBook.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ViewedBookAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ViewedBookAggregateArgs>(args: Prisma.Subset<T, ViewedBookAggregateArgs>): Prisma.PrismaPromise<GetViewedBookAggregateType<T>>

  /**
   * Group by ViewedBook.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ViewedBookGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ViewedBookGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ViewedBookGroupByArgs['orderBy'] }
      : { orderBy?: ViewedBookGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ViewedBookGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetViewedBookGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the ViewedBook model
 */
readonly fields: ViewedBookFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for ViewedBook.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ViewedBookClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  searchLog<T extends Prisma.SearchLogDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.SearchLogDefaultArgs<ExtArgs>>): Prisma.Prisma__SearchLogClient<runtime.Types.Result.GetResult<Prisma.$SearchLogPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  book<T extends Prisma.ViewedBook$bookArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ViewedBook$bookArgs<ExtArgs>>): Prisma.Prisma__BookClient<runtime.Types.Result.GetResult<Prisma.$BookPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the ViewedBook model
 */
export interface ViewedBookFieldRefs {
  readonly id: Prisma.FieldRef<"ViewedBook", 'Int'>
  readonly searchLogId: Prisma.FieldRef<"ViewedBook", 'Int'>
  readonly bookId: Prisma.FieldRef<"ViewedBook", 'Int'>
  readonly bookLink: Prisma.FieldRef<"ViewedBook", 'String'>
  readonly viewedAt: Prisma.FieldRef<"ViewedBook", 'DateTime'>
  readonly similarity: Prisma.FieldRef<"ViewedBook", 'Float'>
}
    

// Custom InputTypes
/**
 * ViewedBook findUnique
 */
export type ViewedBookFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ViewedBook
   */
  select?: Prisma.ViewedBookSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ViewedBook
   */
  omit?: Prisma.ViewedBookOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ViewedBookInclude<ExtArgs> | null
  /**
   * Filter, which ViewedBook to fetch.
   */
  where: Prisma.ViewedBookWhereUniqueInput
}

/**
 * ViewedBook findUniqueOrThrow
 */
export type ViewedBookFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ViewedBook
   */
  select?: Prisma.ViewedBookSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ViewedBook
   */
  omit?: Prisma.ViewedBookOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ViewedBookInclude<ExtArgs> | null
  /**
   * Filter, which ViewedBook to fetch.
   */
  where: Prisma.ViewedBookWhereUniqueInput
}

/**
 * ViewedBook findFirst
 */
export type ViewedBookFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ViewedBook
   */
  select?: Prisma.ViewedBookSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ViewedBook
   */
  omit?: Prisma.ViewedBookOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ViewedBookInclude<ExtArgs> | null
  /**
   * Filter, which ViewedBook to fetch.
   */
  where?: Prisma.ViewedBookWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ViewedBooks to fetch.
   */
  orderBy?: Prisma.ViewedBookOrderByWithRelationInput | Prisma.ViewedBookOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ViewedBooks.
   */
  cursor?: Prisma.ViewedBookWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ViewedBooks from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ViewedBooks.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ViewedBooks.
   */
  distinct?: Prisma.ViewedBookScalarFieldEnum | Prisma.ViewedBookScalarFieldEnum[]
}

/**
 * ViewedBook findFirstOrThrow
 */
export type ViewedBookFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ViewedBook
   */
  select?: Prisma.ViewedBookSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ViewedBook
   */
  omit?: Prisma.ViewedBookOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ViewedBookInclude<ExtArgs> | null
  /**
   * Filter, which ViewedBook to fetch.
   */
  where?: Prisma.ViewedBookWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ViewedBooks to fetch.
   */
  orderBy?: Prisma.ViewedBookOrderByWithRelationInput | Prisma.ViewedBookOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ViewedBooks.
   */
  cursor?: Prisma.ViewedBookWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ViewedBooks from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ViewedBooks.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ViewedBooks.
   */
  distinct?: Prisma.ViewedBookScalarFieldEnum | Prisma.ViewedBookScalarFieldEnum[]
}

/**
 * ViewedBook findMany
 */
export type ViewedBookFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ViewedBook
   */
  select?: Prisma.ViewedBookSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ViewedBook
   */
  omit?: Prisma.ViewedBookOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ViewedBookInclude<ExtArgs> | null
  /**
   * Filter, which ViewedBooks to fetch.
   */
  where?: Prisma.ViewedBookWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ViewedBooks to fetch.
   */
  orderBy?: Prisma.ViewedBookOrderByWithRelationInput | Prisma.ViewedBookOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing ViewedBooks.
   */
  cursor?: Prisma.ViewedBookWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ViewedBooks from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ViewedBooks.
   */
  skip?: number
  distinct?: Prisma.ViewedBookScalarFieldEnum | Prisma.ViewedBookScalarFieldEnum[]
}

/**
 * ViewedBook create
 */
export type ViewedBookCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ViewedBook
   */
  select?: Prisma.ViewedBookSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ViewedBook
   */
  omit?: Prisma.ViewedBookOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ViewedBookInclude<ExtArgs> | null
  /**
   * The data needed to create a ViewedBook.
   */
  data: Prisma.XOR<Prisma.ViewedBookCreateInput, Prisma.ViewedBookUncheckedCreateInput>
}

/**
 * ViewedBook createMany
 */
export type ViewedBookCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many ViewedBooks.
   */
  data: Prisma.ViewedBookCreateManyInput | Prisma.ViewedBookCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * ViewedBook createManyAndReturn
 */
export type ViewedBookCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ViewedBook
   */
  select?: Prisma.ViewedBookSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ViewedBook
   */
  omit?: Prisma.ViewedBookOmit<ExtArgs> | null
  /**
   * The data used to create many ViewedBooks.
   */
  data: Prisma.ViewedBookCreateManyInput | Prisma.ViewedBookCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ViewedBookIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * ViewedBook update
 */
export type ViewedBookUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ViewedBook
   */
  select?: Prisma.ViewedBookSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ViewedBook
   */
  omit?: Prisma.ViewedBookOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ViewedBookInclude<ExtArgs> | null
  /**
   * The data needed to update a ViewedBook.
   */
  data: Prisma.XOR<Prisma.ViewedBookUpdateInput, Prisma.ViewedBookUncheckedUpdateInput>
  /**
   * Choose, which ViewedBook to update.
   */
  where: Prisma.ViewedBookWhereUniqueInput
}

/**
 * ViewedBook updateMany
 */
export type ViewedBookUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update ViewedBooks.
   */
  data: Prisma.XOR<Prisma.ViewedBookUpdateManyMutationInput, Prisma.ViewedBookUncheckedUpdateManyInput>
  /**
   * Filter which ViewedBooks to update
   */
  where?: Prisma.ViewedBookWhereInput
  /**
   * Limit how many ViewedBooks to update.
   */
  limit?: number
}

/**
 * ViewedBook updateManyAndReturn
 */
export type ViewedBookUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ViewedBook
   */
  select?: Prisma.ViewedBookSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ViewedBook
   */
  omit?: Prisma.ViewedBookOmit<ExtArgs> | null
  /**
   * The data used to update ViewedBooks.
   */
  data: Prisma.XOR<Prisma.ViewedBookUpdateManyMutationInput, Prisma.ViewedBookUncheckedUpdateManyInput>
  /**
   * Filter which ViewedBooks to update
   */
  where?: Prisma.ViewedBookWhereInput
  /**
   * Limit how many ViewedBooks to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ViewedBookIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * ViewedBook upsert
 */
export type ViewedBookUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ViewedBook
   */
  select?: Prisma.ViewedBookSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ViewedBook
   */
  omit?: Prisma.ViewedBookOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ViewedBookInclude<ExtArgs> | null
  /**
   * The filter to search for the ViewedBook to update in case it exists.
   */
  where: Prisma.ViewedBookWhereUniqueInput
  /**
   * In case the ViewedBook found by the `where` argument doesn't exist, create a new ViewedBook with this data.
   */
  create: Prisma.XOR<Prisma.ViewedBookCreateInput, Prisma.ViewedBookUncheckedCreateInput>
  /**
   * In case the ViewedBook was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ViewedBookUpdateInput, Prisma.ViewedBookUncheckedUpdateInput>
}

/**
 * ViewedBook delete
 */
export type ViewedBookDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ViewedBook
   */
  select?: Prisma.ViewedBookSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ViewedBook
   */
  omit?: Prisma.ViewedBookOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ViewedBookInclude<ExtArgs> | null
  /**
   * Filter which ViewedBook to delete.
   */
  where: Prisma.ViewedBookWhereUniqueInput
}

/**
 * ViewedBook deleteMany
 */
export type ViewedBookDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ViewedBooks to delete
   */
  where?: Prisma.ViewedBookWhereInput
  /**
   * Limit how many ViewedBooks to delete.
   */
  limit?: number
}

/**
 * ViewedBook.book
 */
export type ViewedBook$bookArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Book
   */
  select?: Prisma.BookSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Book
   */
  omit?: Prisma.BookOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BookInclude<ExtArgs> | null
  where?: Prisma.BookWhereInput
}

/**
 * ViewedBook without action
 */
export type ViewedBookDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ViewedBook
   */
  select?: Prisma.ViewedBookSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ViewedBook
   */
  omit?: Prisma.ViewedBookOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ViewedBookInclude<ExtArgs> | null
}
