
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma. Through it you get access to all the models, enums, and input types.
 * If you're looking for something you can import in the client-side of your application, please refer to the `browser.ts` file instead.
 *
 * 🟢 You can import this file directly.
 */

import * as process from 'node:process'
import * as path from 'node:path'

import * as runtime from "@prisma/client/runtime/client"
import * as $Enums from "./enums"
import * as $Class from "./internal/class"
import * as Prisma from "./internal/prismaNamespace"

export * as $Enums from './enums'
export * from "./enums"
/**
 * ## Prisma Client
 * 
 * Type-safe database client for TypeScript
 * @example
 * ```
 * const prisma = new PrismaClient()
 * // Fetch zero or more Books
 * const books = await prisma.book.findMany()
 * ```
 * 
 * Read more in our [docs](https://pris.ly/d/client).
 */
export const PrismaClient = $Class.getPrismaClientClass()
export type PrismaClient<LogOpts extends Prisma.LogLevel = never, OmitOpts extends Prisma.PrismaClientOptions["omit"] = Prisma.PrismaClientOptions["omit"], ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = $Class.PrismaClient<LogOpts, OmitOpts, ExtArgs>
export { Prisma }

/**
 * Model Book
 * 
 */
export type Book = Prisma.BookModel
/**
 * Model Format
 * 
 */
export type Format = Prisma.FormatModel
/**
 * Model Store
 * 
 */
export type Store = Prisma.StoreModel
/**
 * Model Feedback
 * 
 */
export type Feedback = Prisma.FeedbackModel
/**
 * Model FeedbackCategory
 * 
 */
export type FeedbackCategory = Prisma.FeedbackCategoryModel
/**
 * Model SearchLog
 * 
 */
export type SearchLog = Prisma.SearchLogModel
/**
 * Model SentMessage
 * 
 */
export type SentMessage = Prisma.SentMessageModel
/**
 * Model StoreStatistic
 * 
 */
export type StoreStatistic = Prisma.StoreStatisticModel
/**
 * Model UnsuccessfulSearch
 * 
 */
export type UnsuccessfulSearch = Prisma.UnsuccessfulSearchModel
/**
 * Model User
 * 
 */
export type User = Prisma.UserModel
/**
 * Model Query
 * 
 */
export type Query = Prisma.QueryModel
/**
 * Model WeeklyBroadcast
 * 
 */
export type WeeklyBroadcast = Prisma.WeeklyBroadcastModel
/**
 * Model BookPrice
 * 
 */
export type BookPrice = Prisma.BookPriceModel
/**
 * Model CacheLog
 * 
 */
export type CacheLog = Prisma.CacheLogModel
/**
 * Model ViewedBook
 * 
 */
export type ViewedBook = Prisma.ViewedBookModel
