
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser"

export type * from '../models'
export type * from './prismaNamespace'

export const Decimal = runtime.Decimal


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


export const ModelName = {
  Book: 'Book',
  Format: 'Format',
  Store: 'Store',
  Feedback: 'Feedback',
  FeedbackCategory: 'FeedbackCategory',
  SearchLog: 'SearchLog',
  SentMessage: 'SentMessage',
  StoreStatistic: 'StoreStatistic',
  UnsuccessfulSearch: 'UnsuccessfulSearch',
  User: 'User',
  Query: 'Query',
  WeeklyBroadcast: 'WeeklyBroadcast',
  BookPrice: 'BookPrice',
  CacheLog: 'CacheLog',
  ViewedBook: 'ViewedBook'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/*
 * Enums
 */

export const TransactionIsolationLevel = {
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const BookScalarFieldEnum = {
  id: 'id',
  title: 'title',
  link: 'link',
  available: 'available',
  queryId: 'queryId',
  storeId: 'storeId',
  formatId: 'formatId'
} as const

export type BookScalarFieldEnum = (typeof BookScalarFieldEnum)[keyof typeof BookScalarFieldEnum]


export const FormatScalarFieldEnum = {
  id: 'id',
  title: 'title'
} as const

export type FormatScalarFieldEnum = (typeof FormatScalarFieldEnum)[keyof typeof FormatScalarFieldEnum]


export const StoreScalarFieldEnum = {
  id: 'id',
  title: 'title'
} as const

export type StoreScalarFieldEnum = (typeof StoreScalarFieldEnum)[keyof typeof StoreScalarFieldEnum]


export const FeedbackScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  type: 'type',
  message: 'message',
  categoryId: 'categoryId',
  createdAt: 'createdAt'
} as const

export type FeedbackScalarFieldEnum = (typeof FeedbackScalarFieldEnum)[keyof typeof FeedbackScalarFieldEnum]


export const FeedbackCategoryScalarFieldEnum = {
  id: 'id',
  key: 'key',
  description: 'description'
} as const

export type FeedbackCategoryScalarFieldEnum = (typeof FeedbackCategoryScalarFieldEnum)[keyof typeof FeedbackCategoryScalarFieldEnum]


export const SearchLogScalarFieldEnum = {
  id: 'id',
  queryId: 'queryId',
  userId: 'userId',
  searchedAt: 'searchedAt',
  groupedResults: 'groupedResults'
} as const

export type SearchLogScalarFieldEnum = (typeof SearchLogScalarFieldEnum)[keyof typeof SearchLogScalarFieldEnum]


export const SentMessageScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  sentAt: 'sentAt',
  groupId: 'groupId'
} as const

export type SentMessageScalarFieldEnum = (typeof SentMessageScalarFieldEnum)[keyof typeof SentMessageScalarFieldEnum]


export const StoreStatisticScalarFieldEnum = {
  id: 'id',
  storeId: 'storeId',
  booksFound: 'booksFound',
  lastScrapedAt: 'lastScrapedAt'
} as const

export type StoreStatisticScalarFieldEnum = (typeof StoreStatisticScalarFieldEnum)[keyof typeof StoreStatisticScalarFieldEnum]


export const UnsuccessfulSearchScalarFieldEnum = {
  id: 'id',
  queryId: 'queryId',
  userId: 'userId',
  searchedAt: 'searchedAt'
} as const

export type UnsuccessfulSearchScalarFieldEnum = (typeof UnsuccessfulSearchScalarFieldEnum)[keyof typeof UnsuccessfulSearchScalarFieldEnum]


export const UserScalarFieldEnum = {
  id: 'id',
  telegramId: 'telegramId',
  username: 'username',
  firstSeen: 'firstSeen',
  lastActive: 'lastActive',
  sessionCount: 'sessionCount',
  lastWeeklyTop: 'lastWeeklyTop'
} as const

export type UserScalarFieldEnum = (typeof UserScalarFieldEnum)[keyof typeof UserScalarFieldEnum]


export const QueryScalarFieldEnum = {
  id: 'id',
  query: 'query',
  firstSeen: 'firstSeen'
} as const

export type QueryScalarFieldEnum = (typeof QueryScalarFieldEnum)[keyof typeof QueryScalarFieldEnum]


export const WeeklyBroadcastScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  groupName: 'groupName',
  sentAt: 'sentAt'
} as const

export type WeeklyBroadcastScalarFieldEnum = (typeof WeeklyBroadcastScalarFieldEnum)[keyof typeof WeeklyBroadcastScalarFieldEnum]


export const BookPriceScalarFieldEnum = {
  id: 'id',
  bookId: 'bookId',
  price: 'price',
  recordedAt: 'recordedAt'
} as const

export type BookPriceScalarFieldEnum = (typeof BookPriceScalarFieldEnum)[keyof typeof BookPriceScalarFieldEnum]


export const CacheLogScalarFieldEnum = {
  id: 'id',
  bookId: 'bookId',
  queryId: 'queryId',
  createdAt: 'createdAt'
} as const

export type CacheLogScalarFieldEnum = (typeof CacheLogScalarFieldEnum)[keyof typeof CacheLogScalarFieldEnum]


export const ViewedBookScalarFieldEnum = {
  id: 'id',
  searchLogId: 'searchLogId',
  bookId: 'bookId',
  bookLink: 'bookLink',
  viewedAt: 'viewedAt',
  similarity: 'similarity'
} as const

export type ViewedBookScalarFieldEnum = (typeof ViewedBookScalarFieldEnum)[keyof typeof ViewedBookScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const NullableJsonNullValueInput = {
  DbNull: 'DbNull',
  JsonNull: 'JsonNull'
} as const

export type NullableJsonNullValueInput = (typeof NullableJsonNullValueInput)[keyof typeof NullableJsonNullValueInput]


export const QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
} as const

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]


export const JsonNullValueFilter = {
  DbNull: 'DbNull',
  JsonNull: 'JsonNull',
  AnyNull: 'AnyNull'
} as const

export type JsonNullValueFilter = (typeof JsonNullValueFilter)[keyof typeof JsonNullValueFilter]

